### ISSUE TITLE
using Consul for persistence store throws an error

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#829] opened 2016-11-30 12:18 UTC
on mesos/marathon, with Vamp DCOS 091

[ERROR] [11/30/2016 11:43:52.058] [vamp-akka.actor.default-dispatcher-19] [akka://vamp/user/StreamSupervisor-7/flow-597-0-unknown-operation] Error in stage [Recover(<function1>)]: Tcp command [Connect(vamp-consul.dom.dom:0,None,List(),Some(10 seconds),true)] failed io.vamp.common.http.HttpClientException: Tcp command [Connect(vamp-consul.dom.dom:0,None,List(),Some(10 seconds),true)] failed at io.vamp.common.http.HttpClient$$anonfun$recoverWith$1$1.applyOrElse(HttpClient.scala:107) at io.vamp.common.http.HttpClient$$anonfun$recoverWith$1$1.applyOrElse(HttpClient.scala:96) at akka.stream.impl.fusing.Recover$$anon$11.onUpstreamFailure(Ops.scala:246) at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:733) at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616) at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471) at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423) at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603) at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618) at akka.actor.Actor$class.aroundReceive(Actor.scala:484) at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529) at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) at akka.actor.ActorCell.invoke(ActorCell.scala:495) at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) at akka.dispatch.Mailbox.run(Mailbox.scala:224) at akka.dispatch.Mailbox.exec(Mailbox.scala:234) at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) Caused by: akka.stream.StreamTcpException: Tcp command [Connect(vamp-consul.dom.dom:0,None,List(),Some(10 seconds),true)] failed

**Comment by iamtew** [comment] 2016-12-01 08:19
Can you provide steps for reproducing this?

Vamp marathon service config, consul cluster setup details, version of DC/OS used, etc.

Thanks!

**Comment by iamtew** [comment] 2016-12-01 08:29
Closing due to insufficient information.

**Closed by iamtew** 2016-12-01 08:29 UTC
Labels: bug
