### ISSUE TITLE
Vamp 091 cannot connect to Kubernetes over HTTPS

### ISSUE THREAD

**Issue by thecodeassassin** [magneticio/vamp#819] opened 2016-11-10 14:45 UTC
The following exception is generated when you use a HTTPS endpoint of the Kubernetes API:

```
15:44:13.033 | TRACE | io.vamp.common.http.HttpClient           |                                          | req [HttpMethod(POST) http://192.168.99.100:30183/vamp-persistence/_refresh] - HttpEntity.Strict(application/json,)
15:44:13.036 | ERROR | io.vamp.common.notification.Notification |                                          | Container response error.
15:44:13.041 | ERROR | io.vamp.common.notification.Notification |                                          | The server-side HTTP version is not supported
```

When using the HTTP endpoint, everything seems to work.

**Comment by olafmol** [comment] 2016-11-10 20:49
what version of Vamp and K8s are you running, and on what infrastructure? This will help us to reproduce.

**Comment by thecodeassassin** [comment] 2016-11-10 20:51
0.9.1 of vamp

Versions of kubernetes tried:

1.3.9
1.3.10
1.4.5
⁣
Tried on Google Container Engine and minikube.
​

**Comment by iamtew** [comment] 2016-11-15 15:42
I noticed this as well in my own testing, it seems to be related to missing packages inside our images. You could open a shell to the Vamp container and run the following and see if it helps with the connection errors:

```bash
apk update && \
apk add openssl ca-certificates && \
update-ca-certificates
```

Found it here: https://github.com/Yelp/dumb-init/issues/73

I had the same ` wget: can't execute 'ssl_helper': No such file or directory` error when debugging connections

**Comment by iamtew** [comment] 2016-11-16 08:43
https://github.com/magneticio/vamp/pull/821

**Comment by olafmol** [comment] 2016-11-17 21:45
this issue seems to be introduced in Vamp 091 as Vamp 090 can successfully connect to K8s over HTTPS. Tested using minikube and k8s 1.3 and 1.4. It's also reported with Rancher and Vamp 091 over HTTPS.

**Comment by iamtew** [comment] 2016-11-21 11:47
Following pull request contains a working work-around: https://github.com/magneticio/vamp-docker/pull/9

However it adds a proxy that does HTTPS termination, and requires an additional docker container. I'm hesitant to merge this request to our master branch at this time, because we then need to manage yet another container. 
However I'm leaving it open because maybe someone else wants to try it. 

Once we have a working solution in Vamp itself, I'll close this.

**Comment by iamtew** [comment] 2016-11-21 12:10
There seems to be quite a lot of changes to the internal HTTP client in Vamp:
- https://github.com/magneticio/vamp/compare/0.9.0...0.9.1?diff=split&name=0.9.1
- https://github.com/magneticio/vamp/tree/master/common/src/main/scala/io/vamp/common/http

Most likely something in here has changed and not handling HTTPS correctly.

**Comment by thecodeassassin** [comment] 2016-11-21 12:17
@iamtew yeah i think it has to do with this commit: https://github.com/magneticio/vamp/commit/5a7cb01ec20ff30b251011543ff5533bb117fc44. Apparently the underlying HTTP library was switched, then HTTPS support broke.

**Comment by iamtew** [comment] 2016-11-21 12:49
Akka's HTTPS client: http://doc.akka.io/docs/akka/2.4.10/scala/http/client-side/client-https-support.html

**Comment by thecodeassassin** [comment] 2016-11-21 15:37
The problem has to do with the fact that akka is configured to only talk to HTTP endpoints.

file:
common/src/main/scala/io/vamp/common/http/HttpClient.scala

The following code would switch to https when the URL contains HTTPS:

```
    // Use a secure connection when a secure URL is requested
    def getOutgoingConnection(uri: String) = {
      if (uri contains "https") {
        val looseConfig = SSLLooseConfig().withAcceptAnyCertificate(true).
          withDisableHostnameVerification(true).
          withAllowLegacyHelloMessages(Some(true)).
          withAllowUnsafeRenegotiation(Some(true)).
          withAllowWeakCiphers(true).
          withAllowWeakProtocols(true)

        val sslConfig = AkkaSSLConfig().mapSettings(s ⇒ s.withLoose(looseConfig))
        val ctx = Http().createClientHttpsContext(sslConfig)

        Http().outgoingConnectionHttps(requestUri.authority.host.address, requestUri.authority.port, connectionContext = ctx)
      }
      else {
        Http().outgoingConnection(requestUri.authority.host.address, requestUri.authority.port)
      }
    }
```

followed by:

```
    Source.single(requestWithEntity)
      .via(getOutgoingConnection(uri))
      .recover(recoverWith)
      .mapAsync(1)({
      //rest of code
```

Only of course when using untrusted certificates, this configuration doesn't work and one gets the following error:

```
2016-11-21T15:13:56.624548245Z Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I don't really know how to safely handle untrusted certificates at this point. The problem is that the certificates from GKE are self-signed by default so there should at least be the option to use untrusted certificates in the application.conf.

Hope this helps

**Comment by dragoslav** [comment] 2016-12-05 14:53
I'm not sure if we can easily disable verification at this point, e.g. https://groups.google.com/forum/#!topic/akka-user/DjCQP28l52k
Just reverted back to old https://github.com/dispatch/dispatch implementation (<=0.9.0).

**Comment by dragoslav** [comment] 2016-12-08 15:56
https://github.com/magneticio/vamp/issues/846

**Comment by dragoslav** [comment] 2016-12-16 19:54
Closing it because Vamp `katana` seems to work fine, otherwise we can create a new issue. One way to test it including with `minikube` is: 
```bash
curl -s https://raw.githubusercontent.com/magneticio/vamp-docker/master/vamp-kubernetes/vamp_kube_quickstart.sh | bash -s -- -k
```

**Closed by dragoslav** 2016-12-16 19:54 UTC
Labels: bug
