### ISSUE TITLE
Graphs in GUI don't show activity

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#388] opened 2015-10-07 13:52 UTC
I'm running Vamp 0710 on OS X with the Docker QuickStart (using the latest Docker Toolbox and "Docker Quickstart Terminal.app". While testing the tutorials and doing the Apache benchmark test, i see the metrics update under load shortly, but no bars in the graphs appear. After a few seconds the numeric metrics are also replaced by "-" (minus) signs, and even when running AB again, no activity shows up here. @danielsneijers any thoughts?

**Comment by danielsneijers** [comment] 2015-10-07 14:16
Hey @olafmol, last time that happened it was because of pulse not emitting new events after something the router. It's been a while but I remember there was an issue on that as well. To test if the problem is caused by the UI or Vamp itself, use Postman to post something like:

{
    "tags": ["routes", "routes:your-deployment-id_endpoint", "metrics", "metrics:rtime"],
    "timestamp" : {
       "gte" : "now-10m"
      }
}

You should get recent data with that query

**Comment by olafmol** [comment] 2015-10-07 21:35
tnx @danielsneijers To what API method do i need to post this?

**Comment by olafmol** [comment] 2015-10-21 19:21
Behaviour is partly improved in 0.7.11 release. Graphs and metrics now show activity for the first few minutes. After a while (say 5 to 10 minutes) the numerics go blank (minus sign) and the graphs stop showing. No error messages show up in the logs. A Vamp API hard reset or sync doesn't resolve the issue, undeploying and redeploying also doesn't solve anything. Only stopping Vamp entirely and starting up everything solves it.

**Comment by dragoslav** [comment] 2015-10-21 19:52
we can close this one, it's duplicate of #322

**Closed** 2015-10-22 13:07 UTC
Labels: vamp-ui
