### ISSUE TITLE
"hello-world => run vamp => linux => copy to clipboard" is in complete

### ISSUE THREAD

**Issue by philippsander** [magneticio/vamp#842] opened 2016-12-06 14:13 UTC
When I visit the site http://vamp.io/documentation/installation/hello-world/ and click "copy" in the "run vamp" "linux" section. The code in my clipboard is incomplete:

docker run --privileged \
           --net=host \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v $(which docker):/bin/docker \
           -v "/sys/fs/cgroup:/sys/fs/cgroup" \
           -e "DOCKER_HOST_IP=$(hostname -I | awk

**Comment by brniamut** [comment] 2016-12-06 15:00
Hey Philip,

The issue is fixed now and is online as we speak. We forgot to escape the string that is being copied so the HTML would stop when a single quote was present. I consider this issue now fixed. Thanks for reporting this issue! 

Bastiaan Niamut, Frontend Dev Vamp.io

**Closed by brniamut** 2016-12-06 15:00 UTC
Labels: bug
