### ISSUE TITLE
Port is set to '0' on server when using Docker driver

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#151] opened 2015-06-05 07:00 UTC
When using this blueprint:

```yaml
name: monarchs:1.2
endpoints:
  frontend.port: 9040
clusters:
  frontend:
    services:
      -
        breed:
          name: monarch_front:0.1
          deployable: magneticio/monarch:0.2
          ports:
            port: 8080/http
```
 I get a running deployment with a resolved port, but the port is not "connected". See the "8080" : 0 part is the json output.

```json
[
    {
        "name": "4f12fd98-c805-4694-8c01-e9431d881597",
        "endpoints": {
            "frontend.port": "9040"
        },
        "clusters": {
            "frontend": {
                "services": [
                    {
                        "state": {
                            "name": "Deployed",
                            "started_at": "2015-06-04T20:14:41.453Z"
                        },
                        "breed": {
                            "name": "monarch_front:0.1",
                            "deployable": "magneticio/monarch:0.2",
                            "ports": {
                                "port": "8080/http"
                            },
                            "environment_variables": {},
                            "constants": {},
                            "dependencies": {}
                        },
                        "scale": {
                            "cpu": 0.3,
                            "memory": 512,
                            "instances": 1
                        },
                        "routing": {
                            "weight": 100,
                            "filters": []
                        },
                        "servers": [
                            {
                                "name": "39b10fbf046b3a4c7567",
                                "host": "127.0.0.1",
                                "ports": {
                                    "8080": 0
                                },
                                "deployed": true
                            }
                        ],
                        "dependencies": {},
                        "dialects": {}
                    }
                ],
                "routes": {
                    "8080": 33000
                },
                "dialects": {}
            }
        },
        "ports": {
            "frontend.port": "33000"
        },
        "environment_variables": {},
        "constants": {},
        "hosts": {
            "frontend": "127.0.0.1"
        }
    }
]
```

**Comment by plamola** [comment] 2015-06-05 07:13
Duplicate of #121

**Closed by plamola** 2015-06-05 07:13 UTC
Labels: bug
