### ISSUE TITLE
Synchronisation of host:port combinations for servers seems to not pick up port changes when a taks is rescheduled on Marathon

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp#226] opened 2015-06-25 15:10 UTC
We have a case where a task is scheduled to host with a specific host:port combination. However, the task fails and is rescheduled on the same or another host. During that restart/reschedule, Vamp does not pickup the newly assigned port.

**Comment by dragoslav** [comment] 2015-06-30 11:02
Couldn't reproduce it with Marathon/Docker setup and since we didn't have this problem afterwards let's close it.

**Closed by dragoslav** 2015-06-30 11:02 UTC
Labels: bug
