### ISSUE TITLE
Demo application still not deploying on k8s

### ISSUE THREAD

**Issue by thecodeassassin** [magneticio/vamp#864] opened 2016-12-18 10:01 UTC
Same issue as #822 

@dragoslav this is still not working. I'm currently testing on GKE.

http://tca0.nl/lc0

```
Hi, I'm Vamp! How are you? 

RUNNING SINCE	18-12-2016 10:38:09
VERSION	0.9.1-6-gfe664ba
UI VERSION	0.9.1-1-g769c1af
PERSISTENCE	elasticsearch
KEY VALUE STORE	etcd
GATEWAY DRIVER	haproxy 1.6.x
CONTAINER DRIVER	
WORKFLOW DRIVER	kubernetes
```

k8s version is 1.4.6

**Comment by dragoslav** [comment] 2016-12-18 10:22
Version you use is far behind current master:
```
VERSION 	0.9.1-42-gbbc771e
UI VERSION 	0.9.1-19-g8419161
```
Could you build Vamp from the source or pull the latest Vamp katana? If you use k8s quick start script, add argument `-k` (or `--katana`) - you may still need to do docker pull...

**Comment by thecodeassassin** [comment] 2016-12-18 11:15
⁣hi Drago,

This is using the latest katana docker image for Vamp.

**Comment by dragoslav** [comment] 2016-12-18 15:17
Could you compare Docker image id of Vamp on GKE and one you pull locally?

**Comment by thecodeassassin** [comment] 2016-12-19 08:42
Hi,

Yes, they are the same:

```
 ✘ stephen@Stephens-MacBook-Pro  /srv/mycujoo/vamp/vamp-docker-origin/vamp-kubernetes   master ●  kubectl describe pod vamp-4131430990-h8jyb |grep ID
    Container ID:	docker://e3183c74256e4735020a904ef8716d7d9e764424fd414b1053c5c531ddd05501
    Image ID:		docker://sha256:**9d9f65ed135f**b3a4e860637ec7ba6f3f6aaad927f5d1dab9b784918716133ba3
```


```
 stephen@Stephens-MacBook-Pro  ~  docker image list | grep magneticio
magneticio/vamp                               katana-kubernetes   **9d9f65ed135f**        2 days ago          172 MB
magneticio/vamp                               <none>              fc669a55a9e8        4 weeks ago         172 MB
```

**Comment by olafmol** [comment] 2016-12-19 08:47
I checked on minikube 13x, 140 and Google CE, with k8s 143,146 and 151 and I cannot reproduce from my side (i.e. It works as expected)

**Comment by dragoslav** [comment] 2016-12-24 12:32
Instead of `katana` could you reproduce this using `0.9.2`?

**Comment by olafmol** [comment] 2017-01-02 08:32
@thecodeassassin could you let us know if this still an issue? Closing this for now, feel free to re-open when needed.

**Closed by olafmol** 2017-01-02 08:32 UTC

**Comment by thecodeassassin** [comment] 2017-01-02 08:34
@olafmol It works when i deploy it on a fresh cluster. It seems that there is still a cached version somewhere. This issue can be closed :)

**Comment by olafmol** [comment] 2017-01-02 08:36
@thecodeassassin 👍
